---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: software-factory-og
  namespace: {{ namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  targetNamespaces:
  - {{ namespace }}
