apiVersion: redhatgov.io/v1alpha1
kind: TsscPlatform
metadata:
  name: software-factory
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  tsscPlatform:
    providers:
      ciTool: jenkins
      containerRegistry: nexus
