apiVersion: redhatgov.io/v1alpha1
kind: TsscPlatform
metadata:
  name: software-factory
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  tsscPlatform:
    helmRepository: 'https://ploigos.github.io/ploigos-charts'
    services:
      artifactRepository:
        managed: true
        name: nexus
      containerRegistry:
        managed: true
        name: nexus
      continuousDeployment:
        managed: true
        name: argocd
      continuousIntegration:
        managed: true
        name: jenkins
      sourceControl:
        managed: true
        name: gitea
      staticCodeAnalysis:
        managed: true
        name: sonarqube
      uat:
        managed: true
        name: selenium
