kind: Secret
apiVersion: v1
metadata:
  name: aws-credentials
  namespace: {{ namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  credentials: >-
		{{ lookup('file', lookup('env', 'AWS_CREDENTIALS_FILE')) | b64encode }}
type: Opaque
