apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '50'
  name: s3-sink-connector
  namespace: "{{ namespace }}"
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: org.apache.camel.kafkaconnector.awss3.CamelAwss3SinkConnector
  config:
    camel.component.aws-s3.accessKey: >-
      ${file:/opt/kafka/external-configuration/connector-config/credentials:access_key}
    camel.component.aws-s3.secretKey: >-
      ${file:/opt/kafka/external-configuration/connector-config/credentials:secret_key}
    camel.sink.endpoint.autoCreateBucket: true
    camel.sink.path.bucketNameOrArn: {{ namespace }}-processed
    key.converter: org.apache.kafka.connect.storage.StringConverter
    topics: processed-eraw
    value.converter: org.apache.camel.kafkaconnector.awss3.converters.S3ObjectConverter
  tasksMax: 1
