{% set creds_file=lookup('env', 'AWS_CREDENTIALS_FILE') %}
kind: Secret
apiVersion: v1
metadata:
  name: aws-credentials
  namespace: {{ namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  credentials: >-
    access_key={{ lookup('ini', 'aws_access_key_id section=default file='+creds_file) }}
    secret_key={{ lookup('ini', 'aws_secret_access_key section=default file='+creds_file) }}
type: Opaque
